#!/bin/bash
# Copyright megabaks
# Distributed under the terms of the GNU General Public License v3 or later
############################################################################
################ check_openrc ##############################################
[[ -f "/etc/init.d/functions.sh" ]] && . /etc/init.d/functions.sh
############################################################################
################ env #######################################################
PORT_ETC="/etc/portage"
atom="${1}"
category="${atom%%/*}"
passed_uses="${@#${1//\*/\\*}}"
############################################################################
################ colors ####################################################
green="\033[01;32m"
red="\033[01;31m"
restore="\033[00m"
############################################################################
################ file or dir... ############################################
file_or_dir(){
	founded="$(ls -d1 ${PORT_ETC}/${1} 2>/dev/null)"
	if [[ -z "${founded}" ]];then
		founded="${PORT_ETC}/${1}"
		touch "${founded}"
	fi
	for target in ${founded};do
		if [[ -f "${target}" ]];then
			file="${target}"
			${2};${3};${4};
		elif [[ -d "${target}" ]];then
			for f in `find ${target} -type f \! -name '*~' \! -name '*.bak'` i_like_you_my_little_gentoo;do
				if grep -q -m1 "${atom//\*/\\*}[[:space:]]" "${file}";then
					file="${f}"
					${2};${3};${4};
				else
					if [[ "${f}" == "i_like_you_my_little_gentoo" ]];then
						file="${PORT_ETC}/${category}"
						${2};${3};${4};
					fi
				fi
			done
		fi
	done
}
############################################################################
################ sort_passed_uses ##########################################
sort_passed_uses(){
	for opt in ${1};do
		opt="${opt//\*/\\*}"
		uses="$(tr "[:space:]" $'\n' <<< ${uses} | grep -v -e "^${opt#-}$" -e "^\-${opt#-}$" | tr $'\n' " ")"
		uses+=" $(tr "[:space:]" $'\n' <<< ${1} | grep -e "^${opt#-}$" -e "^\-${opt#-}$" | tail -n1)"
		unset opt
	done
	echo ${uses}
	unset uses
}
############################################################################
################ nothing ###################################################
nothing(){
	echo -e "${green}no changes${restore}"
	eend 0 2>/dev/null
	exit 0
}
############################################################################
################ sort_uses #################################################
sort_uses(){
	entry="$(grep "${atom//\*/\\*}[[:space:]]" "${file}" | tail -n1)"
	comment="$(cut -d\# -f2- <<< "${entry}")"
	if [[ -n "${entry}" ]];then
		for option in \
			"$(grep "^${atom//\*/\\*}[[:space:]]" ${file} | sed -e "s|${atom//\*/\\*} ||" -e "s|#.*${comment}||" | tr "[:space:]" $'\n' | uniq | tr $'\n' " ")";do
			atom_opts+="${option}"
		done
	fi
	uses="$(sort_passed_uses "${atom_opts} ${passed_uses}")"
	uses="$(sed -e "s|^- | |g" -e "s| -- ||g" -e "s| - | |g" <<< ${uses})"
	if [[ -n "${comment}" ]];then
		if [[ "x${entry}" == "x${atom} ${uses} #${comment}" ]];then
			nothing
		fi
		if [[ -z "${entry}" ]];then
			echo -e "new:${green} ${atom} ${uses} #${comment}${restore}"
			echo "${atom} ${uses} #${comment}" >> "${file}"
			eend $? 2>/dev/null
		else
			echo -e "old:${red} ${entry}${restore}"
			echo -e "new:${green} ${atom} ${uses} #${comment}${restore}"
			sed  "s|${entry//\*/\\*}|${atom} ${uses} #${comment}|" -i "${file}"
			eend $? 2>/dev/null
		fi
	else
		if [[ "x${entry}" == "x${atom} ${uses}" ]];then
			nothing
		fi
		if [[ -z "${entry}" ]];then
			echo -e "new:${green} ${atom} ${uses}${restore}"
			echo "${atom} ${uses}" >> "${file}"
			eend $? 2>/dev/null
		else
			echo -e "old:${red} ${entry}${restore}"
			echo -e "new:${green} ${atom} ${uses}${restore}"
			sed  "s|${entry//\*/\\*}|${atom} ${uses}|" -i "${file}"
			eend $? 2>/dev/null
		fi
	fi
	unset atom atom_opts option options uses comment
} 2>/dev/null
############################################################################
################ package.use ###############################################
atom_use(){
	file_or_dir "package.use" "set -f" "sort_uses" "set +f" || return 1
}
############################################################################
atom_use;
